version: '3.1'

services:
  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - "3304:3306"
    environment:
      MYSQL_DATABASE: bee-master
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis
    ports:
      - "6378:6379"
    volumes:
      - bee-master-redis-data:/data
    command: redis-server --appendonly yes
volumes:
  bee-master-redis-data:
