server:
  port: 8096
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: files
  datasource:
    url: jdbc:mysql://localhost:3304/bee-master
    username: root
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration/mysql
  redis:
    host: localhost
    port: 6378
    database: 5
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        jdbc:
          time_zone: UTC

eureka:
  client:
    enabled: false

gaia:
  kafka:
    bootstrap-servers: localhost:9092
    group-id: dev_business
    topics:
      commands: dev_gaia_commands
      events: dev_gaia_events
  security:
    jwt:
      issuer: thoughtworks
      audience: gaia
      secret: some_secret

file:
  upload:
    path: ~/tmp/
  static:
    access:
      path: /api/file/
  handler: file

aliyun:
  email:
    region_id: cn-hangzhou
    access_key: some_access_key
    secret: some_secret
    account: no-reply@notice.hello-bees.com
    alias: no-reply
  oss:
    endpoint: gaia-dev.oss-cn-beijing.aliyuncs.com
    access-key: some_access_key
    secret-key: some_secret
    region: oss-cn-beijing
feign:
  business:
    url: https://dev.beeart.hello-bees.com/
