CREATE TABLE IF NOT EXISTS bm_training_camp (
    id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
		clientName VARCHAR(64) NOT NULL,
    startDateTime  TIMESTAMP NULL,
    endDateTime   TIMESTAMP NULL,
		status VARCHAR(64),
		createdTime       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
		lastModifiedTime TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY  (id),
    INDEX `IX_BM_TRAININGCAMP`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS bm_task (
  id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  description text null,
  sortNumber int(2) null,
  visibleToStudent int(1) NOT NULL,
  startDateTime  TIMESTAMP NULL,
  endDateTime   TIMESTAMP NULL,
  createdTime       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastModifiedTime TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY  (id),
  INDEX `IX_BM_TASK`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=1;

